import { ArrowUpRight, ArrowRight, Plane, Package, ShieldCheck, MoveUpRight } from 'lucide-react';
import Waitlist from './waitlist';
export default function Home() {
 return <>
  <a className="skip" href="#main">Skip to content</a>
  <header className="nav wrap"><a className="brand" href="#" aria-label="Encapsul home"><span className="brand-mark">e</span>encapsul<span className="brand-dot">.</span></a><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#first-route">Our first route</a><a className="nav-cta" href="#waitlist">Join the waitlist <ArrowUpRight size={17}/></a></nav></header>
  <main id="main">
   <section className="hero wrap">
    <div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> A NEW WAY TO MOVE THINGS IN NIGERIA</p><h1>Empty kilos.<br/>Full <span>potential.</span></h1><p className="hero-description">Your unused baggage allowance could go further.<br className="desktop-break"/> Earn when you fly. Send something that can’t wait.</p><a className="button" href="#waitlist">Join the waitlist <ArrowUpRight size={20}/></a><p className="cta-note">Early access & beta testing. Be part of the first flight.</p></div>
    <div className="route-visual" aria-label="Planned Lagos to Abuja pilot, turning unused flight capacity into delivery"><div className="visual-top"><span>THE SPACE BETWEEN<br/>BECOMES POSSIBILITY.</span><MoveUpRight size={32}/></div><div className="route-diagram"><div className="route-city"><small>FROM</small><strong>LOS</strong><span>Lagos</span></div><div className="flight-line"><span/><Plane size={31}/><span/></div><div className="route-city destination"><small>TO</small><strong>ABV</strong><span>Abuja</span></div></div><div className="capacity"><div><span>Unused capacity</span><span>New possibilities</span></div><div className="capacity-track"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div className="ticket"><div className="ticket-icon"><Package size={23}/></div><div><strong>A little room. A big difference.</strong><p>Already flying. Ready for more.</p></div><ArrowUpRight size={21}/></div><div className="visual-bottom"><span>PLANNED PILOT · LAGOS → ABUJA</span><span>01 / NG</span></div></div>
   </section>
   <div className="principles"><div className="wrap"><span><Plane/> Earn from unused kilos</span><span><Package/> Designed for same-day delivery</span><span><ShieldCheck/> Screening built into the journey</span></div></div>
   <section id="how-it-works" className="section wrap"><div className="section-heading"><p className="eyebrow">01 / A BETTER USE OF SPACE</p><h2>One flight.<br/>Two ways to get more.</h2><p>Planes are already connecting our cities. We’re building a way for the space on board to connect more of what matters.</p></div><div className="audiences"><article><div className="card-top"><span className="label">FOR TRAVELLERS</span><Plane/></div><h3>Pack light.<br/>Make it count.</h3><p>Pledge the baggage allowance you don’t need and earn from confirmed spare capacity. Keep your trip exactly that: your trip.</p><div className="card-foot"><ShieldCheck size={19}/> You never carry or handle anyone’s parcel.</div></article><article><div className="card-top"><span className="label">FOR SENDERS</span><Package/></div><h3>Across cities.<br/>Within the day.</h3><p>From an urgent document to a small business part, we’re working towards screened, tracked delivery on scheduled passenger flights.</p><div className="card-foot"><ArrowRight size={19}/> Built for the things that can’t wait.</div></article></div></section>
   <section className="journey wrap"><div><p className="eyebrow">THE JOURNEY, SIMPLIFIED</p><h2>We handle the cargo.<br/>You get on with your day.</h2></div><ol><li><span>01</span><div><h3>Find the room</h3><p>Travellers pledge unused allowance. Available capacity is confirmed with the airline.</p></div></li><li><span>02</span><div><h3>Screen. Stage. Fly.</h3><p>Encapsul handles the parcel separately, with screening before loading and passenger bags taking priority.</p></div></li><li><span>03</span><div><h3>Make the connection</h3><p>The parcel flies to its destination for onward delivery. The traveller earns from their confirmed kilos.</p></div></li></ol></section>
   <section id="first-route" className="pilot"><div className="wrap pilot-inner"><div><p className="eyebrow">02 / STARTING CLOSE. THINKING BIG.</p><h2>Lagos first.<br/>Abuja next stop.</h2><p>One corridor to get it right. Our planned pilot starts with Lagos to Abuja, before expanding to more Nigerian cities.</p></div><div className="pilot-detail"><span className="pilot-badge">IN DEVELOPMENT</span><div className="pilot-airports">LOS <ArrowRight/> ABV</div><p>We’re preparing for launch. Operations depend on the required approvals, airline agreements, and a successful pilot.</p></div></div></section>
   <section id="waitlist" className="section wrap waitlist-section"><div><p className="eyebrow">03 / GET IN EARLY</p><h2>The next big thing<br/>could travel light.</h2><p>Help shape a smarter way to move things.<br/>Join the waitlist for early access and the opportunity to test the beta.</p><div className="waitlist-caption"><span className="status-dot"/> Built for Nigeria. Starting with you.</div></div><Waitlist/></section>
  </main><footer className="wrap"><a className="brand" href="#">encapsul.</a><span>More from every journey.</span><small>© {new Date().getFullYear()} Encapsul</small></footer>
 </>;
}
