'use client';
import { useState } from 'react';
import { ArrowUpRight, CheckCircle2 } from 'lucide-react';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
export default function Waitlist(){
 const [interest,setInterest]=useState('both'); const [beta,setBeta]=useState(true); const [state,setState]=useState('idle'); const [error,setError]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){ e.preventDefault(); const data=new FormData(e.currentTarget);setState('loading');setError('');try{const response=await fetch('/api/waitlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),interest,beta,website:data.get('website')})}); if(!response.ok)throw new Error(response.status===400?'Please enter a valid email address.':'We couldn’t save your place. Please try again.');setState('success');}catch(err){setError(err instanceof Error?err.message:'Something went wrong. Please try again.');setState('idle');}}
 return <div className="waitlist-card">{state==='success'?<div className="success" role="status"><CheckCircle2 size={42}/><h3>You’re on the list.</h3><p>Thanks for being part of what’s next. We’ll email you when early access or beta opportunities are ready.</p></div>:<form onSubmit={submit}><h3>Your journey starts here.</h3><label className="field-label" htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={254}/><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><fieldset><legend>I’m interested in</legend><RadioGroup className="interest-options" value={interest} onValueChange={v=>setInterest(String(v))} aria-label="Your interest">{[['sending','Sending'],['travelling','Travelling'],['both','Both']].map(([value,label])=><label key={value} className={interest===value?'selected':''}><RadioGroupItem value={value}/>{label}</label>)}</RadioGroup></fieldset><label className="beta-check"><Checkbox checked={beta} onCheckedChange={checked=>setBeta(checked===true)}/> I’d also like to be a beta tester</label><button className="button" disabled={state==='loading'}>{state==='loading'?'Saving your place…':'Join the waitlist'}<ArrowUpRight size={19}/></button>{error&&<p className="form-error" role="alert">{error}</p>}<p className="privacy-note">By joining, you agree to receive emails from Encapsul about early access{beta?' and beta testing':''}. We’ll store your email and preferences for this purpose.</p></form>}</div>;
}
